services:
  web:
    build:
      context: .
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-mongodb://root:root@localhost:27017/auri?authSource=admin}
      AUTH_SECRET: ${AUTH_SECRET:-change-me}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
